/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamiento;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author NuCLeO
 */
public class espacios extends javax.swing.JFrame implements ActionListener{
    conexion conecc = new conexion();
    metodos insertar = new metodos();
    registro reg = new registro();
    Pagoingreso pi = new Pagoingreso();
    Pagosalir ps = new Pagosalir();
    nota not = new nota();
    

    /**
     * Creates new form espacios
     */
    public espacios() {
        initComponents();
        regresarBtn.addActionListener(this);
        update();
        tbselect.setBackground(new java.awt.Color(0, 153, 255));
        tbselect.setText("Pago por Horas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auto1 = new javax.swing.JLabel();
        auto2 = new javax.swing.JLabel();
        auto3 = new javax.swing.JLabel();
        auto4 = new javax.swing.JLabel();
        auto5 = new javax.swing.JLabel();
        auto6 = new javax.swing.JLabel();
        auto7 = new javax.swing.JLabel();
        auto8 = new javax.swing.JLabel();
        auto9 = new javax.swing.JLabel();
        auto10 = new javax.swing.JLabel();
        auto11 = new javax.swing.JLabel();
        auto12 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btndisp1 = new javax.swing.JButton();
        btndisp2 = new javax.swing.JButton();
        btndisp7 = new javax.swing.JButton();
        btndisp8 = new javax.swing.JButton();
        btndisp3 = new javax.swing.JButton();
        btndisp9 = new javax.swing.JButton();
        btndisp4 = new javax.swing.JButton();
        btndisp10 = new javax.swing.JButton();
        btndisp5 = new javax.swing.JButton();
        btndisp11 = new javax.swing.JButton();
        btndisp6 = new javax.swing.JButton();
        btndisp12 = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        pago12 = new javax.swing.JLabel();
        pago7 = new javax.swing.JLabel();
        pago8 = new javax.swing.JLabel();
        pago9 = new javax.swing.JLabel();
        pago10 = new javax.swing.JLabel();
        pago11 = new javax.swing.JLabel();
        pago1 = new javax.swing.JLabel();
        pago2 = new javax.swing.JLabel();
        pago3 = new javax.swing.JLabel();
        pago4 = new javax.swing.JLabel();
        pago5 = new javax.swing.JLabel();
        pago6 = new javax.swing.JLabel();
        tbselect = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        acceso1 = new javax.swing.JLabel();
        acceso2 = new javax.swing.JLabel();
        acceso3 = new javax.swing.JLabel();
        acceso4 = new javax.swing.JLabel();
        acceso5 = new javax.swing.JLabel();
        acceso6 = new javax.swing.JLabel();
        acceso7 = new javax.swing.JLabel();
        acceso8 = new javax.swing.JLabel();
        acceso9 = new javax.swing.JLabel();
        acceso10 = new javax.swing.JLabel();
        acceso11 = new javax.swing.JLabel();
        acceso12 = new javax.swing.JLabel();
        bperdido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ESPACIOS");
        setBackground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        auto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto1.setText("AUTO 1");

        auto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto2.setText("AUTO 2");

        auto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto3.setText("AUTO 3");

        auto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto4.setText("AUTO 4");

        auto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto5.setText("AUTO 5");

        auto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto6.setText("AUTO 6");

        auto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto7.setText("AUTO 7");

        auto8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto8.setText("AUTO 8");

        auto9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto9.setText("AUTO 9");

        auto10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto10.setText("AUTO 10");

        auto11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto11.setText("AUTO 11");

        auto12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auto12.setText("AUTO 12");

        btndisp1.setBackground(new java.awt.Color(0, 153, 255));
        btndisp1.setText("DISPONIBLE 1");
        btndisp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp1ActionPerformed(evt);
            }
        });

        btndisp2.setBackground(new java.awt.Color(0, 153, 255));
        btndisp2.setText("DISPONIBLE 2");
        btndisp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp2ActionPerformed(evt);
            }
        });

        btndisp7.setBackground(new java.awt.Color(0, 153, 255));
        btndisp7.setText("DISPONIBLE 7");
        btndisp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp7ActionPerformed(evt);
            }
        });

        btndisp8.setBackground(new java.awt.Color(0, 153, 255));
        btndisp8.setText("DISPONIBLE 8");
        btndisp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp8ActionPerformed(evt);
            }
        });

        btndisp3.setBackground(new java.awt.Color(0, 153, 255));
        btndisp3.setText("DISPONIBLE 3");
        btndisp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp3ActionPerformed(evt);
            }
        });

        btndisp9.setBackground(new java.awt.Color(0, 153, 255));
        btndisp9.setText("DISPONIBLE 9");
        btndisp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp9ActionPerformed(evt);
            }
        });

        btndisp4.setBackground(new java.awt.Color(0, 153, 255));
        btndisp4.setText("DISPONIBLE 4");
        btndisp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp4ActionPerformed(evt);
            }
        });

        btndisp10.setBackground(new java.awt.Color(0, 153, 255));
        btndisp10.setText("DISPONIBLE 10");
        btndisp10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp10ActionPerformed(evt);
            }
        });

        btndisp5.setBackground(new java.awt.Color(0, 153, 255));
        btndisp5.setText("DISPONIBLE 5");
        btndisp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp5ActionPerformed(evt);
            }
        });

        btndisp11.setBackground(new java.awt.Color(0, 153, 255));
        btndisp11.setText("DISPONIBLE 11");
        btndisp11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp11ActionPerformed(evt);
            }
        });

        btndisp6.setBackground(new java.awt.Color(0, 153, 255));
        btndisp6.setText("DISPONIBLE 6");
        btndisp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp6ActionPerformed(evt);
            }
        });

        btndisp12.setBackground(new java.awt.Color(0, 153, 255));
        btndisp12.setText("DISPONIBLE 12");
        btndisp12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisp12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btndisp7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btndisp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndisp8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btndisp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addComponent(btndisp3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndisp4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndisp5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndisp6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addComponent(btndisp9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndisp10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndisp11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndisp12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndisp1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndisp7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndisp12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        regresarBtn.setText("REGRESAR");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        btnupdate.setText("ACTUALIZA");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        pago12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago12.setText("PAGO 12");

        pago7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago7.setText("PAGO7");

        pago8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago8.setText("PAGO8");

        pago9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago9.setText("PAGO 9");

        pago10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago10.setText("PAGO 10");

        pago11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago11.setText("PAGO 11");

        pago1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago1.setText("PAGO1");

        pago2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago2.setText("PAGO2");

        pago3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago3.setText("PAGO3");

        pago4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago4.setText("PAGO4");

        pago5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago5.setText("PAGO5");

        pago6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pago6.setText("PAGO6");

        tbselect.setText("Pago por Dias");
        tbselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbselectActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click para Cambiar");

        acceso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso1.setText("ACCESO1");

        acceso2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso2.setText("ACCESO2");

        acceso3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso3.setText("ACCESO3");

        acceso4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso4.setText("ACCESO4");

        acceso5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso5.setText("ACCESO5");

        acceso6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso6.setText("ACCESO6");

        acceso7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso7.setText("ACCESO7");

        acceso8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso8.setText("ACCESO8");

        acceso9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso9.setText("ACCESO9");

        acceso10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso10.setText("ACCESO10");

        acceso11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso11.setText("ACCESO11");

        acceso12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceso12.setText("ACCESO12");

        bperdido.setText("BOLETO PERDIDO");
        bperdido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bperdidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bperdido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbselect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pago1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(acceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(acceso5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acceso6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(auto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(auto2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(auto3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(auto4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(auto5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(auto6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(pago2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(auto7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(auto8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(auto9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(auto10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(auto11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(auto12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pago7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(acceso7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(acceso8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(acceso9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pago10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pago12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(acceso10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(acceso11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(acceso12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(acceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(acceso4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnupdate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acceso1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acceso3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acceso4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acceso5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acceso6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pago1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbselect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(bperdido)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auto7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auto9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pago7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pago9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceso7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceso8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceso9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceso11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceso10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceso12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndisp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp1ActionPerformed
            String btn1="DISPONIBLE 1";
            String btn2="OCUPADO 1";
            if (btn1.equals(btndisp1.getText())) {
                reg.nomespaut.setText("auto1");
                reg.nomespacolor.setText("y1");
                pi.nomespaut1.setText("auto1");
                pi.nomespacolor1.setText("y1");
                
                pi.nomespapago1.setText("pagoa1");
                reg.nomespago.setText("pagoa1");
                
                pi.accesopi.setText("acceso1");
                reg.accesore.setText("acceso1");
                
                reg.lugarTxt.setText("1");
                pi.setlugar.setText("1");
                
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp1.getText())) {
                //update espacios
                String A="auto1";//nombre lugar db 
                String B="DISPONIBLE 1";// nombre placa en espacios
                String C="y1";//nombre lugar en db para boolean y cambiar color al boton
                try {insertar.inserTespacios(A, B, C, true, "pagoa1", -1, "acceso1", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                
                if ("PENDIENTE".equals(pago1.getText())) {
                    ps.pshorain.setText(acceso1.getText());
                    ps.psmatricula.setText(auto1.getText());
                    ps.setVisible(true);
                }
                //update
                update();
            }
            
    }//GEN-LAST:event_btndisp1ActionPerformed

    private void btndisp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp2ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 2";
            String btn2="OCUPADO 2";
            if (btn1.equals(btndisp2.getText())) {
                reg.nomespaut.setText("auto2");
                reg.nomespacolor.setText("y2");
                pi.nomespaut1.setText("auto2");
                pi.nomespacolor1.setText("y2");
                pi.nomespapago1.setText("pagoa2");
                reg.nomespago.setText("pagoa2");
                pi.accesopi.setText("acceso2");
                reg.accesore.setText("acceso2");
                reg.lugarTxt.setText("2");
                pi.setlugar.setText("2");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp2.getText())) {
                //update espacios
                try {insertar.inserTespacios("auto2", "DISPONIBLE 2", "y2", true, "pagoa2", -1, "acceso2", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                
                if ("PENDIENTE".equals(pago2.getText())) {
                    ps.pshorain.setText(acceso2.getText());
                    ps.psmatricula.setText(auto2.getText());
                    ps.setVisible(true);
                }
                //update 
                update();
            }
    }//GEN-LAST:event_btndisp2ActionPerformed

    private void btndisp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp3ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 3";
            String btn2="OCUPADO 3";
            if (btn1.equals(btndisp3.getText())) {
                reg.nomespaut.setText("auto3");
                reg.nomespacolor.setText("y3");
                pi.nomespaut1.setText("auto3");
                pi.nomespacolor1.setText("y3");
                pi.nomespapago1.setText("pagoa3");
                reg.nomespago.setText("pagoa3");
                pi.accesopi.setText("acceso3");
                reg.accesore.setText("acceso3");
                reg.lugarTxt.setText("3");
                pi.setlugar.setText("3");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp3.getText())) {
                try {insertar.inserTespacios("auto3", "DISPONIBLE 3", "y3", true, "pagoa3", -1, "acceso3", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                
                if ("PENDIENTE".equals(pago3.getText())) {
                    ps.pshorain.setText(acceso3.getText());
                    ps.psmatricula.setText(auto3.getText());
                    ps.setVisible(true);
                }
                
                update();
            }
    }//GEN-LAST:event_btndisp3ActionPerformed

    private void btndisp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp4ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 4";
            String btn2="OCUPADO 4";
            if (btn1.equals(btndisp4.getText())) {
                reg.nomespaut.setText("auto4");
                reg.nomespacolor.setText("y4");
                pi.nomespaut1.setText("auto4");
                pi.nomespacolor1.setText("y4");
                pi.nomespapago1.setText("pagoa4");
                reg.nomespago.setText("pagoa4");
                pi.accesopi.setText("acceso4");
                reg.accesore.setText("acceso4");
                reg.lugarTxt.setText("4");
                pi.setlugar.setText("4");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp4.getText())) {
                try {insertar.inserTespacios("auto4", "DISPONIBLE 4", "y4", true, "pagoa4", -1, "acceso4", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                
                if ("PENDIENTE".equals(pago4.getText())) {
                    ps.pshorain.setText(acceso4.getText());
                    ps.psmatricula.setText(auto4.getText());
                    ps.setVisible(true);
                }
                
                update();
            }
    }//GEN-LAST:event_btndisp4ActionPerformed

    private void btndisp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp5ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 5";
            String btn2="OCUPADO 5";
            if (btn1.equals(btndisp5.getText())) {
                reg.nomespaut.setText("auto5");
                reg.nomespacolor.setText("y5");
                pi.nomespaut1.setText("auto5");
                pi.nomespacolor1.setText("y5");
                pi.nomespapago1.setText("pagoa5");
                reg.nomespago.setText("pagoa5");
                pi.accesopi.setText("acceso5");
                reg.accesore.setText("acceso5");
                reg.lugarTxt.setText("5");
                pi.setlugar.setText("5");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp5.getText())) {
                try {insertar.inserTespacios("auto5", "DISPONIBLE 5", "y5", true, "pagoa5", -1, "acceso5", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago5.getText())) {
                    ps.pshorain.setText(acceso5.getText());
                    ps.psmatricula.setText(auto5.getText());
                    ps.setVisible(true);
                }
                update();
            }
    }//GEN-LAST:event_btndisp5ActionPerformed

    private void btndisp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp6ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 6";
            String btn2="OCUPADO 6";
            if (btn1.equals(btndisp6.getText())) {
                reg.nomespaut.setText("auto6");
                reg.nomespacolor.setText("y6");
                pi.nomespaut1.setText("auto6");
                pi.nomespacolor1.setText("y6");
                pi.nomespapago1.setText("pagoa6");
                reg.nomespago.setText("pagoa6");
                pi.accesopi.setText("acceso6");
                reg.accesore.setText("acceso6");
                reg.lugarTxt.setText("6");
                pi.setlugar.setText("6");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp6.getText())) {
                try {insertar.inserTespacios("auto6", "DISPONIBLE 6", "y6", true, "pagoa6", -1, "acceso6", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago6.getText())) {
                    ps.pshorain.setText(acceso6.getText());
                    ps.psmatricula.setText(auto6.getText());
                    ps.setVisible(true);
                }
                update();
            }
    }//GEN-LAST:event_btndisp6ActionPerformed

    private void btndisp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp7ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 7";
            String btn2="OCUPADO 7";
            if (btn1.equals(btndisp7.getText())) {
                reg.nomespaut.setText("auto7");
                reg.nomespacolor.setText("y7");
                pi.nomespaut1.setText("auto7");
                pi.nomespacolor1.setText("y7");
                pi.nomespapago1.setText("pagoa7");
                reg.nomespago.setText("pagoa7");
                pi.accesopi.setText("acceso7");
                reg.accesore.setText("acceso7");
                reg.lugarTxt.setText("7");
                pi.setlugar.setText("7");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp7.getText())) {
                try {insertar.inserTespacios("auto7", "DISPONIBLE 7", "y7", true, "pagoa7", -1, "acceso7", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago7.getText())) {
                    ps.pshorain.setText(acceso7.getText());
                    ps.psmatricula.setText(auto7.getText());
                    ps.setVisible(true);
                }
                
                update();
            }
    }//GEN-LAST:event_btndisp7ActionPerformed

    private void btndisp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp8ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 8";
            String btn2="OCUPADO 8";
            if (btn1.equals(btndisp8.getText())) {
                reg.nomespaut.setText("auto8");
                reg.nomespacolor.setText("y8");
                pi.nomespaut1.setText("auto8");
                pi.nomespacolor1.setText("y8");
                pi.nomespapago1.setText("pagoa8");
                reg.nomespago.setText("pagoa8");
                pi.accesopi.setText("acceso8");
                reg.accesore.setText("acceso8");
                reg.lugarTxt.setText("8");
                pi.setlugar.setText("8");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp8.getText())) {
                try {insertar.inserTespacios("auto8", "DISPONIBLE 8", "y8", true, "pagoa8", -1, "acceso8", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago8.getText())) {
                    ps.pshorain.setText(acceso8.getText());
                    ps.psmatricula.setText(auto8.getText());
                    ps.setVisible(true);
                }
                update();
            }
    }//GEN-LAST:event_btndisp8ActionPerformed

    private void btndisp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp9ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 9";
            String btn2="OCUPADO 9";
            if (btn1.equals(btndisp9.getText())) {
                reg.nomespaut.setText("auto9");
                reg.nomespacolor.setText("y9");
                pi.nomespaut1.setText("auto9");
                pi.nomespacolor1.setText("y9");
                pi.nomespapago1.setText("pagoa9");
                reg.nomespago.setText("pagoa9");
                pi.accesopi.setText("acceso9");
                reg.accesore.setText("acceso9");
                reg.lugarTxt.setText("9");
                pi.setlugar.setText("9");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp9.getText())) {
                try {insertar.inserTespacios("auto9", "DISPONIBLE 9", "y9", true, "pagoa9", -1, "acceso9", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago9.getText())) {
                    ps.pshorain.setText(acceso9.getText());
                    ps.psmatricula.setText(auto9.getText());
                    ps.setVisible(true);
                }
                update();
            }
    }//GEN-LAST:event_btndisp9ActionPerformed

    private void btndisp10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp10ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 10";
            String btn2="OCUPADO 10";
            if (btn1.equals(btndisp10.getText())) {
                reg.nomespaut.setText("auto10");
                reg.nomespacolor.setText("y10");
                pi.nomespaut1.setText("auto10");
                pi.nomespacolor1.setText("y10");
                pi.nomespapago1.setText("pagoa10");
                reg.nomespago.setText("pagoa10");
                pi.accesopi.setText("acceso10");
                reg.accesore.setText("acceso10");
                reg.lugarTxt.setText("10");
                pi.setlugar.setText("10");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp10.getText())) {
                try {insertar.inserTespacios("auto10", "DISPONIBLE 10", "y10", true, "pagoa10", -1, "acceso10", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago10.getText())) {
                    ps.pshorain.setText(acceso10.getText());
                    ps.psmatricula.setText(auto10.getText());
                    ps.setVisible(true);
                }
                update();
            }
    }//GEN-LAST:event_btndisp10ActionPerformed

    private void btndisp11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp11ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 11";
            String btn2="OCUPADO 11";
            if (btn1.equals(btndisp11.getText())) {
                reg.nomespaut.setText("auto11");
                reg.nomespacolor.setText("y11");
                pi.nomespaut1.setText("auto11");
                pi.nomespacolor1.setText("y11");
                pi.nomespapago1.setText("pagoa11");
                reg.nomespago.setText("pagoa11");
                pi.accesopi.setText("acceso11");
                reg.accesore.setText("acceso11");
                reg.lugarTxt.setText("11");
                pi.setlugar.setText("11");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp11.getText())) {
                try {insertar.inserTespacios("auto11", "DISPONIBLE 11", "y11", true, "pagoa11", -1, "acceso11", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago11.getText())) {
                    ps.pshorain.setText(acceso11.getText());
                    ps.psmatricula.setText(auto11.getText());
                    ps.setVisible(true);
                }
                update();
            }
    }//GEN-LAST:event_btndisp11ActionPerformed

    private void btndisp12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisp12ActionPerformed
        // TODO add your handling code here:
            String btn1="DISPONIBLE 12";
            String btn2="OCUPADO 12";
            if (btn1.equals(btndisp12.getText())) {
                reg.nomespaut.setText("auto12");
                reg.nomespacolor.setText("y12");
                pi.nomespaut1.setText("auto12");
                pi.nomespacolor1.setText("y12");
                pi.nomespapago1.setText("pagoa12");
                reg.nomespago.setText("pagoa12");
                pi.accesopi.setText("acceso12");
                reg.accesore.setText("acceso12");
                reg.lugarTxt.setText("12");
                pi.setlugar.setText("12");
                if (tbselect.isSelected()) {
                    reg.setVisible(true);
                }else{
                    pi.setVisible(true);
                }
            }
            else if (btn2.equals(btndisp12.getText())) {
                try {insertar.inserTespacios("auto12", "DISPONIBLE 12", "y12", true, "pagoa12", -1, "acceso12", "");
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                if ("PENDIENTE".equals(pago12.getText())) {
                    ps.pshorain.setText(acceso12.getText());
                    ps.psmatricula.setText(auto12.getText());
                    ps.setVisible(true);
                }
                update();
            }
    }//GEN-LAST:event_btndisp12ActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        update();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tbselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbselectActionPerformed
        if (tbselect.isSelected()) {
            tbselect.setBackground(new java.awt.Color(255, 51, 51));
            tbselect.setText("Pago por Dias");
        }else{
            tbselect.setBackground(new java.awt.Color(0, 153, 255));
            tbselect.setText("Pago por Horas");
        }
    }//GEN-LAST:event_tbselectActionPerformed

    private void bperdidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperdidoActionPerformed
        not.setVisible(true);
    }//GEN-LAST:event_bperdidoActionPerformed
    
    public void update(){
        update updt = new update();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new espacios().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acceso1;
    public static javax.swing.JLabel acceso10;
    public static javax.swing.JLabel acceso11;
    public static javax.swing.JLabel acceso12;
    public static javax.swing.JLabel acceso2;
    public static javax.swing.JLabel acceso3;
    public static javax.swing.JLabel acceso4;
    public static javax.swing.JLabel acceso5;
    public static javax.swing.JLabel acceso6;
    public static javax.swing.JLabel acceso7;
    public static javax.swing.JLabel acceso8;
    public static javax.swing.JLabel acceso9;
    public static javax.swing.JLabel auto1;
    public static javax.swing.JLabel auto10;
    public static javax.swing.JLabel auto11;
    public static javax.swing.JLabel auto12;
    public static javax.swing.JLabel auto2;
    public static javax.swing.JLabel auto3;
    public static javax.swing.JLabel auto4;
    public static javax.swing.JLabel auto5;
    public static javax.swing.JLabel auto6;
    public static javax.swing.JLabel auto7;
    public static javax.swing.JLabel auto8;
    public static javax.swing.JLabel auto9;
    private javax.swing.JButton bperdido;
    public static javax.swing.JButton btndisp1;
    public static javax.swing.JButton btndisp10;
    public static javax.swing.JButton btndisp11;
    public static javax.swing.JButton btndisp12;
    public static javax.swing.JButton btndisp2;
    public static javax.swing.JButton btndisp3;
    public static javax.swing.JButton btndisp4;
    public static javax.swing.JButton btndisp5;
    public static javax.swing.JButton btndisp6;
    public static javax.swing.JButton btndisp7;
    public static javax.swing.JButton btndisp8;
    public static javax.swing.JButton btndisp9;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel pago1;
    public static javax.swing.JLabel pago10;
    public static javax.swing.JLabel pago11;
    public static javax.swing.JLabel pago12;
    public static javax.swing.JLabel pago2;
    public static javax.swing.JLabel pago3;
    public static javax.swing.JLabel pago4;
    public static javax.swing.JLabel pago5;
    public static javax.swing.JLabel pago6;
    public static javax.swing.JLabel pago7;
    public static javax.swing.JLabel pago8;
    public static javax.swing.JLabel pago9;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JToggleButton tbselect;
    // End of variables declaration//GEN-END:variables

    
    
    @Override
    public void actionPerformed(ActionEvent e) {
        //Listener
        JButton presionBoton = (JButton) e.getSource();
        if (presionBoton == regresarBtn) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }


}
