/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamiento;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author nucleo
 */
public class Pagosalir extends javax.swing.JFrame {
    metodos insertar = new metodos();
    /**
     * Creates new form Pagosalir
     */
    public Pagosalir() {
        initComponents();
        pshoraout.setText(""+LocalTime.now());
        this.setTitle("Pago al Salir");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pshoraintitulo = new javax.swing.JLabel();
        pshorain = new javax.swing.JLabel();
        selechora1 = new javax.swing.JComboBox<>();
        pstotal = new javax.swing.JLabel();
        etitotal = new javax.swing.JLabel();
        cobrar = new javax.swing.JButton();
        matri = new javax.swing.JLabel();
        psmatricula = new javax.swing.JLabel();
        pshoraintitulo1 = new javax.swing.JLabel();
        pshoraout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("\"EL RAYON\"");

        pshoraintitulo.setText("HORA DE ENTRADA");

        pshorain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pshorain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pshorain.setText("acceso");

        selechora1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE LAS HORAS A PAGAR", "1 HORA", "2 HORAS", "3 HORAS", "4 HORAS", "5 HORAS", "6 HORAS", "7 HORAS", "8 HORAS", "9 HORAS" }));
        selechora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selechora1ActionPerformed(evt);
            }
        });

        pstotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pstotal.setText("total");

        etitotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etitotal.setText("TOTAL: $");

        cobrar.setText("COBRAR");
        cobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarActionPerformed(evt);
            }
        });

        matri.setText("MATRICULA");

        psmatricula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        psmatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        psmatricula.setText("matricula");

        pshoraintitulo1.setText("HORA DE SALIDA");

        pshoraout.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pshoraout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pshoraout.setText("salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cobrar)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selechora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(pshoraintitulo)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pshoraintitulo1)
                                    .addGap(30, 30, 30)))
                            .addComponent(pshorain, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etitotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pstotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pshoraout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(matri)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(psmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pshoraintitulo)
                    .addComponent(pshorain))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pshoraintitulo1)
                    .addComponent(pshoraout))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matri)
                    .addComponent(psmatricula))
                .addGap(18, 18, 18)
                .addComponent(selechora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pstotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etitotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(cobrar)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selechora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selechora1ActionPerformed
        if (selechora1.getSelectedIndex()==0) {
            pstotal.setText("0");
        }
        if (selechora1.getSelectedIndex()==1) {
            pstotal.setText("10");
        }
        else if (selechora1.getSelectedIndex()==2) {
            pstotal.setText("20");
        }
        else if (selechora1.getSelectedIndex()==3) {
            pstotal.setText("25");
        }
        else if (selechora1.getSelectedIndex()==4) {
            pstotal.setText("30");
        }
        else if (selechora1.getSelectedIndex()==5) {
            pstotal.setText("35");
        }
        else if (selechora1.getSelectedIndex()==6) {
            pstotal.setText("40");
        }
        else if (selechora1.getSelectedIndex()==7) {
            pstotal.setText("45");
        }
        else if (selechora1.getSelectedIndex()==8) {
            pstotal.setText("50");
        }
        else if (selechora1.getSelectedIndex()==9) {
            pstotal.setText("55");
        }

        
    }//GEN-LAST:event_selechora1ActionPerformed

    private void cobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarActionPerformed
        if (selechora1.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null, "Seleccione una hora", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                    insertar.inserTpago(0, "", pshoraout.getText(), 0, Integer.parseInt(pstotal.getText()), ""+LocalDate.now(), pshorain.getText(), psmatricula.getText(), 0);
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla pago");

                // area de impresion a pdf
                try {
                JasperReport reporte = null;
                String path = "src\\estacionamiento\\ticketpagoout.jasper";
                Map parametro = new HashMap();
                parametro.put("entrada", pshorain.getText());
                parametro.put("salida", pshoraout.getText());
                parametro.put("matricula", psmatricula.getText());
                parametro.put("total", pstotal.getText());


                reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, new JREmptyDataSource());
                JasperViewer view = new JasperViewer(jprint, false);
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
                } catch (JRException ex) {
                Logger.getLogger(administrador.class.getName()).log(Level.SEVERE, null, ex);
                }

                dispose();
        }
    }//GEN-LAST:event_cobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagosalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagosalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagosalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagosalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagosalir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cobrar;
    private javax.swing.JLabel etitotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel matri;
    public javax.swing.JLabel pshorain;
    private javax.swing.JLabel pshoraintitulo;
    private javax.swing.JLabel pshoraintitulo1;
    private javax.swing.JLabel pshoraout;
    public static javax.swing.JLabel psmatricula;
    private javax.swing.JLabel pstotal;
    private javax.swing.JComboBox<String> selechora1;
    // End of variables declaration//GEN-END:variables
}
