/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamiento;

import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author nucleo
 */
public class Pagoingreso extends javax.swing.JFrame {
    conexion conn = new conexion();
    registro reg=new registro();
    metodos insertar = new metodos();
    /**
     * Creates new form Pagoingreso
     */
    public Pagoingreso() {
        initComponents();
        this.setLocationRelativeTo(null);
        horain.setText(""+LocalTime.now());
        fechain.setText(""+LocalDate.now());
        
        nomespaut1 = new javax.swing.JLabel("");
        nomespacolor1 = new javax.swing.JLabel("");
        nomespapago1 = new javax.swing.JLabel("");
        accesopi = new javax.swing.JLabel("");
        
        int id = insertar.scanFolios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloin = new javax.swing.JLabel();
        titulofyh = new javax.swing.JLabel();
        horain = new javax.swing.JLabel();
        fechain = new javax.swing.JLabel();
        selechora = new javax.swing.JComboBox<>();
        placainlabel = new javax.swing.JLabel();
        placain = new javax.swing.JTextField();
        btncerrarpi = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        pagoinlabel = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        etilugar = new javax.swing.JLabel();
        setlugar = new javax.swing.JLabel();
        titulofyh1 = new javax.swing.JLabel();
        fechaout = new javax.swing.JLabel();
        horaout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloin.setText("PAGO AL INGRESAR");

        titulofyh.setText("FECHA Y HORA DE INGRESO:");

        horain.setBackground(new java.awt.Color(0, 0, 255));
        horain.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        horain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horain.setText("HORA");

        fechain.setBackground(new java.awt.Color(0, 0, 255));
        fechain.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fechain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechain.setText("FECHA");

        selechora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE LAS HORAS A PAGAR", "1 HORA", "2 HORAS", "3 HORAS", "4 HORAS", "5 HORAS", "6 HORAS", "7 HORAS", "8 HORAS", "9 HORAS", "PAGARA AL SALIR" }));
        selechora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selechoraActionPerformed(evt);
            }
        });

        placainlabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        placainlabel.setText("No. Placa");
        placainlabel.setToolTipText("");

        btncerrarpi.setText("CERRAR");
        btncerrarpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarpiActionPerformed(evt);
            }
        });

        btnimprimir.setText("IMPRIMIR");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        pagoinlabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pagoinlabel.setText("TOTAL A PAGAR: $");

        total.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        total.setText("TOTAL");

        etilugar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etilugar.setText("Lugar");

        setlugar.setText("LUGAR");

        titulofyh1.setText("FECHA Y HORA DE SALIDA:");

        fechaout.setBackground(new java.awt.Color(0, 0, 255));
        fechaout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fechaout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaout.setText("FECHA SALIDA");

        horaout.setBackground(new java.awt.Color(0, 0, 255));
        horaout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        horaout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horaout.setText("HORA SALIDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(tituloin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pagoinlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechaout, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(horaout, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechain, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(horain, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 6, Short.MAX_VALUE)))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btncerrarpi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnimprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(placainlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etilugar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placain)
                            .addComponent(setlugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(titulofyh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(selechora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(titulofyh1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tituloin)
                .addGap(52, 52, 52)
                .addComponent(selechora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulofyh)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechain)
                    .addComponent(horain))
                .addGap(18, 18, 18)
                .addComponent(titulofyh1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaout)
                    .addComponent(horaout))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagoinlabel)
                    .addComponent(total))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placainlabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setlugar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(etilugar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncerrarpi)
                    .addComponent(btnimprimir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selechoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selechoraActionPerformed
        if (selechora.getSelectedIndex()==0) {
            total.setText("0");
            fechaout.setText(""+LocalDate.now());
            horaout.setText(""+LocalTime.now());
        }
        if (selechora.getSelectedIndex()==1) {
            total.setText("10");
            fechaout.setText(""+LocalDate.now());
            
            hora=1;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==2) {
            total.setText("20");
            fechaout.setText(""+LocalDate.now());
            hora=2;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==3) {
            total.setText("25");
            fechaout.setText(""+LocalDate.now());
            hora=3;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==4) {
            total.setText("30");
            fechaout.setText(""+LocalDate.now());
            hora=4;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==5) {
            total.setText("35");
            fechaout.setText(""+LocalDate.now());
            hora=5;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==6) {
            total.setText("40");
            fechaout.setText(""+LocalDate.now());
            hora=6;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==7) {
            total.setText("45");
            fechaout.setText(""+LocalDate.now());
            hora=7;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==8) {
            total.setText("50");
            fechaout.setText(""+LocalDate.now());
            hora=8;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        else if (selechora.getSelectedIndex()==9) {
            total.setText("55");
            fechaout.setText(""+LocalDate.now());
            hora=9;
            LocalTime thora = LocalTime.now();
            LocalTime newTime = thora.plusHours(hora);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            horaout.setText(""+newTime);
            
        }
        
        //Dilan no modifiques estos ultimos  con el 0 se indicara que el pago es al final y el otro mostrara el boton de registro
        else if (selechora.getSelectedIndex()==10) {
            total.setText("0");
            fechaout.setText(""+LocalDate.now());
            horaout.setText(""+LocalTime.now());
            
        }
        
    }//GEN-LAST:event_selechoraActionPerformed

    private void btncerrarpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarpiActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarpiActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        if (placain.getText().isEmpty() || selechora.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "NO SELECCIONO HORAS Ó \nMATRICULA ESTA VACIO", "IMPORTANTE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            reg.nomespaut.setText(nomespaut1.getText());
            reg.nomespacolor.setText(nomespacolor1.getText());
            reg.nomespago.setText(nomespapago1.getText());

            int id_lugar = insertar.scanIdLugar();
            int id_cli = insertar.scanId();
            dispose();
            try {
                insertar.inserTauto(placain.getText(), "Publico", "Publico", "Publico", id_cli);
            } catch (Exception e) {System.out.println(e);
            }System.out.println("Ingreso tabla auto");
            try {
                insertar.inserTcliente(id_cli, "Publico", "Publico", "Publico");
            } catch (Exception e) {System.out.println(e);
            }System.out.println("Ingreso tabla cliente");
            try {
                insertar.inserTpago(id_cli, fechaout.getText(), horaout.getText(), hora, Integer.parseInt(total.getText()), fechain.getText(), horain.getText(), placain.getText(), Integer.parseInt(setlugar.getText()));
            } catch (Exception e) {System.out.println(e);
            }System.out.println("Ingreso tabla pago");
            try {
                insertar.inserTregistro(id_lugar, fechain.getText(), horain.getText(), "Publico");
            } catch (Exception e) {System.out.println(e);
            }System.out.println("Ingreso tabla registro");
            try {
                insertar.inserTestacion(id_lugar, Integer.parseInt(setlugar.getText()), placain.getText(), true);
            } catch (Exception e) {System.out.println(e);
            }System.out.println("Ingreso tabla estacionamiento");
            try {
                insertar.inserTfolio("Publico", id_cli);
            } catch (Exception e) {System.out.println(e);
            }System.out.println("Ingreso tabla folio");

            //update espacios >>nomespaut.getText(), nomespacolor.getText(), nomespapago1.getText() = toman datos de una variable que envia la clase espacios pero esta oculta<<
            try {
                insertar.inserTespacios(nomespaut1.getText(), placain.getText(), nomespacolor1.getText(), false, nomespapago1.getText(), Integer.parseInt(total.getText()), accesopi.getText(), horain.getText());
            } catch (Exception e) {System.out.println(e);
            }System.out.println("Ingreso tabla espacios");

            // area de impresion a pdf
            try {
            JasperReport reporte = null;
            String path = "src\\estacionamiento\\ticketpagoin.jasper";
            Map parametro = new HashMap();
            parametro.put("fechain", fechain.getText());
            parametro.put("horain", horain.getText());
            parametro.put("fechaout", fechaout.getText());
            parametro.put("horaout", horaout.getText());
            parametro.put("lugar", setlugar.getText());
            parametro.put("matricula", placain.getText());
            parametro.put("pago", total.getText());

            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, new JREmptyDataSource());
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
            } catch (JRException ex) {
            Logger.getLogger(administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            // LIMPIEZA Y ACTUALIZACION
            limpiar();
            int id = insertar.scanFolios();
            horain.setText("" + LocalTime.now());
            fechain.setText("" + LocalDate.now());
            update updt = new update();
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagoingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagoingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagoingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagoingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagoingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrarpi;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JLabel etilugar;
    public javax.swing.JLabel fechain;
    public javax.swing.JLabel fechaout;
    public javax.swing.JLabel horain;
    public javax.swing.JLabel horaout;
    private javax.swing.JLabel pagoinlabel;
    public javax.swing.JTextField placain;
    public javax.swing.JLabel placainlabel;
    private javax.swing.JComboBox<String> selechora;
    public javax.swing.JLabel setlugar;
    private javax.swing.JLabel titulofyh;
    private javax.swing.JLabel titulofyh1;
    private javax.swing.JLabel tituloin;
    public javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JLabel nomespaut1;
    public javax.swing.JLabel nomespacolor1;
    public javax.swing.JLabel nomespapago1;
    public javax.swing.JLabel accesopi;
    
    
    public int hora=0;
    
    
    public void limpiar(){
    placain.setText("");
    
    }
    
    
    
    
}
