/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamiento;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author NuCLeO
 */
public class registro extends javax.swing.JFrame implements ActionListener{
    metodos insertar = new metodos();
    
    
    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
        this.setTitle("Registro");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        regresar.addActionListener(this);
        imprimir.addActionListener(this);
        hora.addActionListener(this);
        
        nomespaut = new javax.swing.JLabel("");
        nomespacolor = new javax.swing.JLabel("");
        nomespago = new javax.swing.JLabel("");
        accesore = new javax.swing.JLabel("");
        
        int id = insertar.scanFolios();;
        folioTxt.setText("A"+id);
        
        gethora.setText(""+LocalTime.now());
        hsalida.setText(""+LocalTime.now());
        getfecha.setText(""+LocalDate.now());
        fsalida.setText(""+LocalDate.now());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro = new javax.swing.JPanel();
        folioEtq = new javax.swing.JLabel();
        folioTxt = new javax.swing.JTextField();
        nombreEtq = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        direccionEtq = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JTextField();
        telefonoEtq = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        marcaEtq = new javax.swing.JLabel();
        marcaTxt = new javax.swing.JTextField();
        placaEtq = new javax.swing.JLabel();
        placaTxt = new javax.swing.JTextField();
        modeloEtq = new javax.swing.JLabel();
        modeloTxt = new javax.swing.JTextField();
        colorEtq = new javax.swing.JLabel();
        colorTxt = new javax.swing.JTextField();
        observacionEtq = new javax.swing.JLabel();
        detalleEtq = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        observacionTxt = new javax.swing.JTextArea();
        lugarEtq = new javax.swing.JLabel();
        lugarTxt = new javax.swing.JTextField();
        hora = new javax.swing.JButton();
        gethora = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        getfecha = new javax.swing.JLabel("F");
        Fecha = new javax.swing.JButton();
        totalreg = new javax.swing.JLabel();
        etfesalida = new javax.swing.JLabel();
        ethosalida = new javax.swing.JLabel();
        hsalida = new javax.swing.JLabel();
        fsalida = new javax.swing.JLabel();
        labtotal = new javax.swing.JLabel();
        selectdia = new javax.swing.JComboBox<>();
        selectsemana = new javax.swing.JComboBox<>();
        selectmes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "REGISTRO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 40))); // NOI18N

        folioEtq.setText("Folio: ");

        folioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioTxtActionPerformed(evt);
            }
        });

        nombreEtq.setText("Nombre:");

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        direccionEtq.setText("Direccion:");

        telefonoEtq.setText("Telefono:");

        marcaEtq.setText("Marca:");

        placaEtq.setText("Placas:");

        modeloEtq.setText("Modelo:");

        modeloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTxtActionPerformed(evt);
            }
        });

        colorEtq.setBackground(new java.awt.Color(102, 255, 102));
        colorEtq.setText("Color:");
        colorEtq.setToolTipText("");

        colorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTxtActionPerformed(evt);
            }
        });

        observacionEtq.setText("Observaciones");

        detalleEtq.setText("(Detalles de averio)");

        observacionTxt.setColumns(20);
        observacionTxt.setRows(5);
        scroll.setViewportView(observacionTxt);

        lugarEtq.setText("Lugar asignado:");

        hora.setText("Hora");
        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        imprimir.setText("Imprimir boleto");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        Fecha.setText("Fecha");
        Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActionPerformed(evt);
            }
        });

        totalreg.setText("Total");

        etfesalida.setText("Fecha de Salida");

        ethosalida.setText("Hora de Salida");

        hsalida.setText("Hora");

        fsalida.setText("fecha");

        labtotal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labtotal.setText("TOTAL: $");

        selectdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIAS", "1", "2", "3", "4", "5", "6", " " }));
        selectdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectdiaActionPerformed(evt);
            }
        });

        selectsemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMANAS", "1", "2", "3", " " }));
        selectsemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectsemanaActionPerformed(evt);
            }
        });

        selectmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MESES", "1", "2", "3", "4", "5", "6" }));
        selectmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectmesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registroLayout = new javax.swing.GroupLayout(registro);
        registro.setLayout(registroLayout);
        registroLayout.setHorizontalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(folioEtq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(folioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registroLayout.createSequentialGroup()
                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(registroLayout.createSequentialGroup()
                                    .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registroLayout.createSequentialGroup()
                                            .addGap(75, 75, 75)
                                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(direccionEtq)
                                                .addComponent(nombreEtq)
                                                .addComponent(telefonoEtq)
                                                .addComponent(marcaEtq)
                                                .addComponent(placaEtq)))
                                        .addComponent(observacionEtq, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(detalleEtq, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(5, 5, 5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                                    .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lugarEtq, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labtotal, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                                    .addComponent(totalreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(55, 55, 55)
                                    .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registroLayout.createSequentialGroup()
                                            .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(registroLayout.createSequentialGroup()
                                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(etfesalida)
                                                .addComponent(ethosalida))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(hsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fsalida))))
                                    .addGap(11, 11, 11))
                                .addComponent(nombreTxt)
                                .addComponent(direccionTxt)
                                .addGroup(registroLayout.createSequentialGroup()
                                    .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(telefonoTxt)
                                                .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(registroLayout.createSequentialGroup()
                                            .addComponent(lugarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(selectdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(selectsemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(selectmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 14, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registroLayout.createSequentialGroup()
                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(registroLayout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(hora))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Fecha)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gethora, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(getfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(119, 119, 119)
                            .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(registroLayout.createSequentialGroup()
                                    .addComponent(modeloEtq)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(registroLayout.createSequentialGroup()
                                    .addComponent(colorEtq)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18))
        );
        registroLayout.setVerticalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(folioEtq))
                .addGap(18, 18, 18)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEtq)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionEtq)
                    .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoEtq))
                .addGap(18, 18, 18)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaEtq))
                        .addGap(21, 21, 21)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placaEtq))
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(observacionEtq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detalleEtq))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeloEtq)
                            .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorEtq))))
                .addGap(26, 26, 26)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lugarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectsemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lugarEtq))
                .addGap(12, 12, 12)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addComponent(getfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etfesalida)
                            .addComponent(fsalida))))
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ethosalida)
                            .addComponent(hsalida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalreg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labtotal)))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hora)
                            .addComponent(gethora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActionPerformed
        getfecha.setText(""+LocalDate.now());
    }//GEN-LAST:event_FechaActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        JButton presionBoton = (JButton) evt.getSource();
        if (presionBoton == regresar) {
            Login login = new Login();
            this.dispose();
        }
        if (presionBoton == imprimir) {
            if (folioTxt.getText().isEmpty() || nombreTxt.getText().isEmpty() || direccionTxt.getText().isEmpty() ||
                telefonoTxt.getText().isEmpty() || marcaTxt.getText().isEmpty() || modeloTxt.getText().isEmpty() ||
                placaTxt.getText().isEmpty() || colorTxt.getText().isEmpty() || lugarTxt.getText().isEmpty()
            ) {
                JOptionPane.showMessageDialog(null, "HAY ALGUN CAMPO VACIO", "IMPORTANTE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int id_lugar = insertar.scanIdLugar();
                int id_cli = insertar.scanId();
                dispose();

                try {
                    insertar.inserTauto(placaTxt.getText(), marcaTxt.getText(), modeloTxt.getText(), colorTxt.getText(), id_cli);
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla auto");
                try {
                    insertar.inserTcliente(id_cli, nombreTxt.getText(), direccionTxt.getText(), telefonoTxt.getText());
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla cliente");
                try {
                    insertar.inserTregistro(id_lugar, getfecha.getText(), gethora.getText(), observacionTxt.getText());
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla registro");
                try {
                    insertar.inserTestacion(id_lugar, Integer.parseInt(lugarTxt.getText()), placaTxt.getText(), true);
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla estacionamiento");
                try {
                    insertar.inserTfolio(folioTxt.getText(), id_cli);
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla folio");
                try {
                insertar.inserTpago(id_cli, fsalida.getText(), hsalida.getText(), ftotal, Integer.parseInt(totalreg.getText()), getfecha.getText(), gethora.getText(), placaTxt.getText(), Integer.parseInt(lugarTxt.getText()));
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla pago");

                try {
                    insertar.inserTespacios(nomespaut.getText(), placaTxt.getText(), nomespacolor.getText(), false, nomespago.getText(), Integer.parseInt(totalreg.getText()), accesore.getText(), gethora.getText());
                } catch (Exception e) {System.out.println(e);
                }System.out.println("Ingreso tabla espacios");
                
                // area de impresion a pdf
                try {
                JasperReport reporte = null;
                String path = "src\\estacionamiento\\ticketregistro.jasper";
                Map parametro = new HashMap();
                    parametro.put("folio", folioTxt.getText());
                    parametro.put("fechain", getfecha.getText());
                    parametro.put("horain", gethora.getText());
                    parametro.put("fechaout", fsalida.getText());
                    parametro.put("salidaout", hsalida.getText());
                    parametro.put("cliente", nombreTxt.getText());
                    parametro.put("concepto", total+"");
                    parametro.put("observacion", observacionTxt.getText());
                    parametro.put("lugar", lugarTxt.getText());
                    parametro.put("matricula", placaTxt.getText());
                    parametro.put("pago", totalreg.getText());
                

                reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, new JREmptyDataSource());
                JasperViewer view = new JasperViewer(jprint, false);
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
                } catch (JRException ex) {Logger.getLogger(administrador.class.getName()).log(Level.SEVERE, null, ex);}
                
                //AREA DE LIMPIEZA Y ACTUALIZACION 
                limpiar();
                // ESTAS LINEAS ACTUALIZAN LOS DATOS SI CIERRAS LAS VENTANAS
                int id = insertar.scanFolios();
                folioTxt.setText("A" + id);
                gethora.setText("" + LocalTime.now());
                getfecha.setText("" + LocalDate.now());
                update updt = new update();
            }
        }
    }//GEN-LAST:event_imprimirActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
        gethora.setText(""+LocalTime.now());

    }//GEN-LAST:event_horaActionPerformed

    private void colorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTxtActionPerformed

    private void modeloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void folioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folioTxtActionPerformed

    private void selectdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectdiaActionPerformed
        if (selectdia.getSelectedIndex()==0) {
            dia=0;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fdia=0;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectdia.getSelectedIndex()==1) {
            dia=55;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fdia=1;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectdia.getSelectedIndex()==2) {
            dia=110;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fdia=2;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectdia.getSelectedIndex()==3) {
            dia=165;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fdia=3;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectdia.getSelectedIndex()==4) {
            dia=220;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fdia=4;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectdia.getSelectedIndex()==5) {
            dia=275;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fdia=5;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectdia.getSelectedIndex()==6) {
            dia=330;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fdia=6;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
    }//GEN-LAST:event_selectdiaActionPerformed

    private void selectsemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectsemanaActionPerformed
        if (selectsemana.getSelectedIndex()==0) {
            semana=0;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fsemana=0;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectsemana.getSelectedIndex()==1) {
            semana=385;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fsemana=7;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectsemana.getSelectedIndex()==2) {
            semana=770;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fsemana=17;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectsemana.getSelectedIndex()==3) {
            semana=1155;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fsemana=21;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
    }//GEN-LAST:event_selectsemanaActionPerformed

    private void selectmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectmesActionPerformed
        if (selectmes.getSelectedIndex()==0) {
            mes=0;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            //aumento de fecha
            fmes=0;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectmes.getSelectedIndex()==1) {
            mes=1650;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            fmes=30;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectmes.getSelectedIndex()==2) {
            mes=3300;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            fmes=60;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectmes.getSelectedIndex()==3) {
            mes=4950;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            fmes=90;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectmes.getSelectedIndex()==4) {
            mes=6600;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            fmes=120;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectmes.getSelectedIndex()==5) {
            mes=8250;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            fmes=150;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
        if (selectmes.getSelectedIndex()==6) {
            mes=9900;
            total=dia+semana+mes;
            totalreg.setText(""+total);
            fmes=150;
            ftotal=fdia+fsemana+fmes;
            LocalDate fecha = LocalDate.now();
            LocalDate newDate = fecha.plusDays(ftotal);
            ZoneId defaultZoneId = ZoneId.systemDefault();
            fsalida.setText(""+newDate);
        }
    }//GEN-LAST:event_selectmesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fecha;
    private javax.swing.JLabel colorEtq;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JLabel detalleEtq;
    private javax.swing.JLabel direccionEtq;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JLabel etfesalida;
    private javax.swing.JLabel ethosalida;
    private javax.swing.JLabel folioEtq;
    private javax.swing.JTextField folioTxt;
    private javax.swing.JLabel fsalida;
    private javax.swing.JLabel getfecha;
    private javax.swing.JLabel gethora;
    private javax.swing.JButton hora;
    private javax.swing.JLabel hsalida;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel labtotal;
    private javax.swing.JLabel lugarEtq;
    public javax.swing.JTextField lugarTxt;
    private javax.swing.JLabel marcaEtq;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JLabel modeloEtq;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JLabel nombreEtq;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel observacionEtq;
    private javax.swing.JTextArea observacionTxt;
    private javax.swing.JLabel placaEtq;
    private javax.swing.JTextField placaTxt;
    private javax.swing.JPanel registro;
    private javax.swing.JButton regresar;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JComboBox<String> selectdia;
    private javax.swing.JComboBox<String> selectmes;
    private javax.swing.JComboBox<String> selectsemana;
    private javax.swing.JLabel telefonoEtq;
    private javax.swing.JTextField telefonoTxt;
    public javax.swing.JLabel totalreg;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JLabel nomespaut;
    public javax.swing.JLabel nomespacolor;
    public javax.swing.JLabel nomespacio;
    public javax.swing.JLabel nomespago;
    public javax.swing.JLabel accesore;
    //variables para suma de dias,semanas,meses costos
    public int dia=0;
    public int semana=0;
    public int mes=0;
    public int total=0;
    //variables para suma de dias,semanas,meses calendario
    public int fdia=0;
    public int fsemana=0;
    public int fmes=0;
    public int ftotal=0;
    
    @Override
    public void actionPerformed(ActionEvent e) {
        //Listener
        
    }
    
    public void limpiar() {
        nombreTxt.setText("");
        direccionTxt.setText("");
        telefonoTxt.setText("");
        marcaTxt.setText("");
        modeloTxt.setText("");
        colorTxt.setText("");
        placaTxt.setText("");
        observacionTxt.setText("");
    }
    

}
